name: "Podcast generator"
author: "Rhycce Vanpee"
description: "Generate a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  email:
    description: "The committers email address"
    required: true
    default: "${{ github.actor }}@localhost"
  name:
    description: "The commiters name"
    required: true
    default: "${{ github.actor }}"
  xmlFile:
    description: "The output xml file"
    required: true
    default: "feed.xml"
  ymlFile:
    description: "The YAML file to be converted"
    required: true
    default: "feed.yaml"